### ISSUE TITLE
getDatabase method returns exception

### ISSUE THREAD

**Issue by pporrasebi** [bridgedb/BridgeDbR#13]
I try to download a human dtabase for identifier mapping and I get this message: 

Error in function (type, msg, asError = TRUE) : SSL: no alternative certificate subject name matches target host name 'www.bridgedb.org'

We use this package in an identifiers mapping course at EBI, it would be great if we could still use it as reference example for our course attendants.

**Comment by egonw** [comment]
Hi @pporrasebi, sorry for the inconvenience. It has to do with the cyberattack, and I'm working hard on restoring services.

**Comment by pporrasebi** [comment]
OK, many thanks for such a speedy response. Please let me know when the service is restored, so I can check everything is fine on our side.

**Comment by egonw** [comment]
A quick update. We've moved to Plan B and I've started putting in place new websites, hosted by GitHub. A lot to do and the index page does not link to any gene database yet, and there is a certificate issue to be resolved, but we're getting closed to a solution.

```R
getBridgeNames(website="http://www.bridgedb.org/data/gene_database/")
getBridgeNames(website="https://bridgedb.github.io/data/gene_database/")
```

Once I've got gene databases linked, you can overcome the SSL error thrown by RCurl, by overwriting the default `website` value as in the above example. But this doe not give expected results yet, as the gene databases first need to be available online at a different location.

**Comment by pporrasebi** [comment]
Thanks for the update, Egon. Good luck with the fixes and let me know if there are any checks we can do that migth help.

**Comment by egonw** [comment]
I have uploaded a new package to Bioconductor. I hope it will show up soon: https://www.bioconductor.org/packages/release/bioc/html/BridgeDbR.html

**Comment by egonw** [comment]
Or if you do not want to wait, use this:

```R
install_github("bridgedb/BridgeDbR", ref="RELEASE_3_10")
```

@pporrasebi, looking forward hearing if that solves all your issues.

**Comment by egonw** [comment]
Or:

```R
install_bioc("3.10/BridgeDbR", force=TRUE)
```

**Comment by pporrasebi** [comment]
I have not done in depth testing, but it seems to be able to load up the mappers now and I could run my mapping routine for the course with the github version. So the issue appears to be solved. 

Many thanks, Egon!
