### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by ariutta** [bridgedb/BridgeDbR#16]
the vignette links to [Genes, Transcripts, and Proteins](https://www.bridgedb.org/mapping-databases/ensembl-gene-mappings/), but when I click that link, I get a warning:
>Firefox detected a potential security threat and did not continue to www.bridgedb.org because this website requires a secure connection.

**Comment by Chris-Evelo** [comment]
We "just" moved the BridgeDb.org URL registration from GoDaddy to Strato and I think Luc still has to set up the security certificate again. I will ping him.

**Comment by egonw** [comment]
Fixed and pushed to `release` and `devel`.
