### ISSUE TITLE
Error when running the map() or maps() function

### ISSUE THREAD

**Issue by CDoornbos** [bridgedb/BridgeDbR#31]
**Short overview of the bug**
Hi, I've recently updated to BridgeDbR version 2.10.0 through Bioconductor and now the map() and maps() function always return an error for me. I've tried to run the example as given in the function documentation, but neither seem to work for me anymore.

**Steps to reproduce**
_For instance, the example given in the maps() documentation:_

location <- getDatabase("Bacillus subtilis")
mapper <- loadDatabase(location)
input = data.frame(
  source= c("L"),
  identifier= c("885041")
)
maps(mapper,input)

_Or from the map() documentation:_
location <- getDatabase("Bacillus subtilis")
mapper <- loadDatabase(location)
map(mapper, "L", "885041")

**Error**
Error in data.frame(source = source, identifier = identifier, target = unlist(targetcodes,  : 
  arguments imply differing number of rows: 1, 0

**Additional information**
R version 4.3.0.
BridgeDbR version 2.10.0

Hope you could help me solve this.

**Comment by egonw** [comment]
Okay, thanks for the ping! I will check as soon as possible what is going on.

**Comment by kozo2** [comment]
@CDoornbos Thanks for creating this issue.

@egonw I am also having trouble with this error.
It is stopping https://github.com/kozo2/AHWikipathwaysDbs/blob/main/inst/scripts/make-data.R#L273
and I need your help.

**Comment by CDoornbos** [comment]
@egonw I've crystallized the problem a bit further after my initial post and I hope it might help solving the it.


**When**
The change occured somewhere between R4.1.0 (BiocManager v3.14, BridgeDbR v2.4.0) and R4.2.3 (BiocMananger v3.16, BridgeDbR v2.8.0). I can't seem to pinpoint it any further for now as loading BridgeDbR v2.5.0 using Biocmanager v3.15 resulted in repeated crashes of R.


**Where**
The output of an identifier that could not be mapped using the _map()_ or _maps()_ function changed from an empty data frame line to and error:
_"Error in data.frame(source = source, identifier = identifier, target = unlist(targetcodes,  : 
  arguments imply differing number of rows: 1, 0"_. 
The result is that even when some identifiers can be mapped, an error is thrown and the function is aborted without any results.


**Example from documentation can't be mapped**
Of note, this is unfortunately also the case for the example from the function documentation that I referred to in my initial post. The following identifier can't be mapped using the current Bacillus subtilis _"Bs_Derby_Ensembl_91.bridge"_ database:

```
location <- getDatabase("Bacillus subtilis")
mapper <- loadDatabase(location)

input = data.frame(
  source= c("L"),
  identifier= c("885041")
)
maps(mapper,input) #--> output: error
```

Other identifiers like the one below can be mapped using this same Bacillus subtilis same database:

```
input = data.frame(
  source= c("En"),
  identifier= c("BSn5_00025")
)
maps(mapper,input, target = "S") #--> output: data frame with mapped output as expected
```


**Workaround**
@kozo2 I've found a workaround using the try() function and map() to test the existence of an identifier one at a time and only include the ones that don't give an error:

```
location <- getDatabase("Bacillus subtilis")
mapper <- loadDatabase(location)

identifier = c("BSn5_00025", "abc") #BSn5_00025 is a true identifier, "abc" is a made-up identifier for debugging
df <- c()
for (id in identifier){
  mapped <- try(map(mapper, "En", id, target = "S"), silent = TRUE)
  if(!inherits(mapped,'try-error')){
    df <- rbind(df, mapped)
  }
}
```

The output here is identical to the map() output of only **"BSn5_00025"**.

**Comment by egonw** [comment]
@CDoornbos, I can reproduce the issue and debugging what is going on.

**Comment by egonw** [comment]
Still working on it. I'm adding some tests and I added an `exists(xref)` method.

**Comment by egonw** [comment]
Okay, the `map()` example is fixed (tho not very helpful):

```R
> library(BridgeDbR)
Loading required package: rJava
> location <- getDatabase("Bacillus subtilis")
mapper <- loadDatabase(location)
trying URL 'https://zenodo.org/record/3667670/files/Bs_Derby_Ensembl_91.bridge?download=1'
Content type 'application/octet-stream' length 8190235 bytes (7.8 MB)
==================================================
downloaded 7.8 MB

> map(mapper, "L", "885041")

[1] source     identifier target     mapping    isPrimary 
<0 rows> (or 0-length row.names)
```

**Comment by egonw** [comment]
Okay, it seems that for `Bacillus subtilis` we no longer have NCBI gene identifiers (`Bs_Derby_Ensembl_91.bridge`, cc @tabbassidaloii):

```R
> map(mapper, "En", "BSn5_00025")
  source identifier target       mapping isPrimary
1     En BSn5_00025      T    GO:0008168         T
2     En BSn5_00025     En    BSn5_00025         T
3     En BSn5_00025      T    GO:0008152         T
4     En BSn5_00025      S UPI0001F59798         T
```

**Comment by egonw** [comment]
So, the problem with `maps()` was also interesting: the code was not actually returning something, but this now works too:

```R
> maps(mapper, input)
  source                  identifier target                     mapping
1     Ik YECLLIMZHNYFCK-RRNJGNTNSA-J     Lm                LMFA07050035
2     Ik YECLLIMZHNYFCK-RRNJGNTNSA-J     Sl               SLM:000000493
3     Ik YECLLIMZHNYFCK-RRNJGNTNSA-J     Ik YECLLIMZHNYFCK-RRNJGNTNSA-J
  isPrimary
1         F
2         T
3         T
> mapper <- loadDatabase("/tmp/RtmpRFWc2g/Bs_Derby_Ensembl_91.bridge")
> input = data.frame(
  source= c("En"),
  identifier= c("BSn5_00025")
)
maps(mapper,input, target = "S")
       source identifier target       mapping isPrimary
source     En BSn5_00025      S UPI0001F59798         T
```

And without target:

```R
> maps(mapper,input)
  source identifier target       mapping isPrimary
1     En BSn5_00025      T    GO:0008168         T
2     En BSn5_00025     En    BSn5_00025         T
3     En BSn5_00025      T    GO:0008152         T
4     En BSn5_00025      S UPI0001F59798         T
```

**Comment by egonw** [comment]
Okay, @CDoornbos, @kozo2, @michaelwitting, the following two branches should work, but I would appreciate your independent testing:

* Stable: https://github.com/bridgedb/BridgeDbR/tree/RELEASE_3_17
* Devel: https://github.com/bridgedb/BridgeDbR/tree/devel

**Comment by egonw** [comment]
Okay, the tests have been running green on BioConductor. If it still doesn't work for you, plz reopen the issue.
